services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
